/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniosRouteImport } from './routes/testimonios'
import { Route as TengoUnProblemaRouteImport } from './routes/tengo-un-problema'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QueEsAaRouteImport } from './routes/que-es-aa'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PrimeraReunionRouteImport } from './routes/primera-reunion'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as NecesitoAyudaRouteImport } from './routes/necesito-ayuda'
import { Route as MapaDelSitioRouteImport } from './routes/mapa-del-sitio'
import { Route as LiteraturaRouteImport } from './routes/literatura'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GruposSlugRouteImport } from './routes/grupos.$slug'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as AuthenticatedServicioRouteImport } from './routes/_authenticated/servicio'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedServicioIndexRouteImport } from './routes/_authenticated/servicio.index'
import { Route as AuthenticatedServicioUsuariosRouteImport } from './routes/_authenticated/servicio.usuarios'
import { Route as AuthenticatedServicioPerfilRouteImport } from './routes/_authenticated/servicio.perfil'
import { Route as AuthenticatedServicioReunionesIndexRouteImport } from './routes/_authenticated/servicio.reuniones.index'
import { Route as AuthenticatedServicioGruposIndexRouteImport } from './routes/_authenticated/servicio.grupos.index'
import { Route as AuthenticatedServicioEventosIndexRouteImport } from './routes/_authenticated/servicio.eventos.index'
import { Route as AuthenticatedServicioGruposNuevoRouteImport } from './routes/_authenticated/servicio.grupos.nuevo'
import { Route as AuthenticatedServicioGruposIdRouteImport } from './routes/_authenticated/servicio.grupos.$id'
import { Route as AuthenticatedServicioEventosNuevoRouteImport } from './routes/_authenticated/servicio.eventos.nuevo'
import { Route as AuthenticatedServicioEventosIdRouteImport } from './routes/_authenticated/servicio.eventos.$id'

const TestimoniosRoute = TestimoniosRouteImport.update({
  id: '/testimonios',
  path: '/testimonios',
  getParentRoute: () => rootRouteImport,
} as any)
const TengoUnProblemaRoute = TengoUnProblemaRouteImport.update({
  id: '/tengo-un-problema',
  path: '/tengo-un-problema',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QueEsAaRoute = QueEsAaRouteImport.update({
  id: '/que-es-aa',
  path: '/que-es-aa',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeraReunionRoute = PrimeraReunionRouteImport.update({
  id: '/primera-reunion',
  path: '/primera-reunion',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const NecesitoAyudaRoute = NecesitoAyudaRouteImport.update({
  id: '/necesito-ayuda',
  path: '/necesito-ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaDelSitioRoute = MapaDelSitioRouteImport.update({
  id: '/mapa-del-sitio',
  path: '/mapa-del-sitio',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteraturaRoute = LiteraturaRouteImport.update({
  id: '/literatura',
  path: '/literatura',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposSlugRoute = GruposSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GruposRoute,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventosRoute,
} as any)
const AuthenticatedServicioRoute = AuthenticatedServicioRouteImport.update({
  id: '/servicio',
  path: '/servicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicioIndexRoute =
  AuthenticatedServicioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioUsuariosRoute =
  AuthenticatedServicioUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioPerfilRoute =
  AuthenticatedServicioPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioReunionesIndexRoute =
  AuthenticatedServicioReunionesIndexRouteImport.update({
    id: '/reuniones/',
    path: '/reuniones/',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioGruposIndexRoute =
  AuthenticatedServicioGruposIndexRouteImport.update({
    id: '/grupos/',
    path: '/grupos/',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioEventosIndexRoute =
  AuthenticatedServicioEventosIndexRouteImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioGruposNuevoRoute =
  AuthenticatedServicioGruposNuevoRouteImport.update({
    id: '/grupos/nuevo',
    path: '/grupos/nuevo',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioGruposIdRoute =
  AuthenticatedServicioGruposIdRouteImport.update({
    id: '/grupos/$id',
    path: '/grupos/$id',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioEventosNuevoRoute =
  AuthenticatedServicioEventosNuevoRouteImport.update({
    id: '/eventos/nuevo',
    path: '/eventos/nuevo',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioEventosIdRoute =
  AuthenticatedServicioEventosIdRouteImport.update({
    id: '/eventos/$id',
    path: '/eventos/$id',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRouteWithChildren
  '/grupos': typeof GruposRouteWithChildren
  '/horarios': typeof HorariosRoute
  '/literatura': typeof LiteraturaRoute
  '/mapa-del-sitio': typeof MapaDelSitioRoute
  '/necesito-ayuda': typeof NecesitoAyudaRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/primera-reunion': typeof PrimeraReunionRoute
  '/privacidad': typeof PrivacidadRoute
  '/que-es-aa': typeof QueEsAaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tengo-un-problema': typeof TengoUnProblemaRoute
  '/testimonios': typeof TestimoniosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/servicio': typeof AuthenticatedServicioRouteWithChildren
  '/eventos/$slug': typeof EventosSlugRoute
  '/grupos/$slug': typeof GruposSlugRoute
  '/servicio/perfil': typeof AuthenticatedServicioPerfilRoute
  '/servicio/usuarios': typeof AuthenticatedServicioUsuariosRoute
  '/servicio/': typeof AuthenticatedServicioIndexRoute
  '/servicio/eventos/$id': typeof AuthenticatedServicioEventosIdRoute
  '/servicio/eventos/nuevo': typeof AuthenticatedServicioEventosNuevoRoute
  '/servicio/grupos/$id': typeof AuthenticatedServicioGruposIdRoute
  '/servicio/grupos/nuevo': typeof AuthenticatedServicioGruposNuevoRoute
  '/servicio/eventos/': typeof AuthenticatedServicioEventosIndexRoute
  '/servicio/grupos/': typeof AuthenticatedServicioGruposIndexRoute
  '/servicio/reuniones/': typeof AuthenticatedServicioReunionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRouteWithChildren
  '/grupos': typeof GruposRouteWithChildren
  '/horarios': typeof HorariosRoute
  '/literatura': typeof LiteraturaRoute
  '/mapa-del-sitio': typeof MapaDelSitioRoute
  '/necesito-ayuda': typeof NecesitoAyudaRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/primera-reunion': typeof PrimeraReunionRoute
  '/privacidad': typeof PrivacidadRoute
  '/que-es-aa': typeof QueEsAaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tengo-un-problema': typeof TengoUnProblemaRoute
  '/testimonios': typeof TestimoniosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/grupos/$slug': typeof GruposSlugRoute
  '/servicio/perfil': typeof AuthenticatedServicioPerfilRoute
  '/servicio/usuarios': typeof AuthenticatedServicioUsuariosRoute
  '/servicio': typeof AuthenticatedServicioIndexRoute
  '/servicio/eventos/$id': typeof AuthenticatedServicioEventosIdRoute
  '/servicio/eventos/nuevo': typeof AuthenticatedServicioEventosNuevoRoute
  '/servicio/grupos/$id': typeof AuthenticatedServicioGruposIdRoute
  '/servicio/grupos/nuevo': typeof AuthenticatedServicioGruposNuevoRoute
  '/servicio/eventos': typeof AuthenticatedServicioEventosIndexRoute
  '/servicio/grupos': typeof AuthenticatedServicioGruposIndexRoute
  '/servicio/reuniones': typeof AuthenticatedServicioReunionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRouteWithChildren
  '/grupos': typeof GruposRouteWithChildren
  '/horarios': typeof HorariosRoute
  '/literatura': typeof LiteraturaRoute
  '/mapa-del-sitio': typeof MapaDelSitioRoute
  '/necesito-ayuda': typeof NecesitoAyudaRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/primera-reunion': typeof PrimeraReunionRoute
  '/privacidad': typeof PrivacidadRoute
  '/que-es-aa': typeof QueEsAaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tengo-un-problema': typeof TengoUnProblemaRoute
  '/testimonios': typeof TestimoniosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/servicio': typeof AuthenticatedServicioRouteWithChildren
  '/eventos/$slug': typeof EventosSlugRoute
  '/grupos/$slug': typeof GruposSlugRoute
  '/_authenticated/servicio/perfil': typeof AuthenticatedServicioPerfilRoute
  '/_authenticated/servicio/usuarios': typeof AuthenticatedServicioUsuariosRoute
  '/_authenticated/servicio/': typeof AuthenticatedServicioIndexRoute
  '/_authenticated/servicio/eventos/$id': typeof AuthenticatedServicioEventosIdRoute
  '/_authenticated/servicio/eventos/nuevo': typeof AuthenticatedServicioEventosNuevoRoute
  '/_authenticated/servicio/grupos/$id': typeof AuthenticatedServicioGruposIdRoute
  '/_authenticated/servicio/grupos/nuevo': typeof AuthenticatedServicioGruposNuevoRoute
  '/_authenticated/servicio/eventos/': typeof AuthenticatedServicioEventosIndexRoute
  '/_authenticated/servicio/grupos/': typeof AuthenticatedServicioGruposIndexRoute
  '/_authenticated/servicio/reuniones/': typeof AuthenticatedServicioReunionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacto'
    | '/eventos'
    | '/grupos'
    | '/horarios'
    | '/literatura'
    | '/mapa-del-sitio'
    | '/necesito-ayuda'
    | '/preguntas-frecuentes'
    | '/primera-reunion'
    | '/privacidad'
    | '/que-es-aa'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tengo-un-problema'
    | '/testimonios'
    | '/perfil'
    | '/servicio'
    | '/eventos/$slug'
    | '/grupos/$slug'
    | '/servicio/perfil'
    | '/servicio/usuarios'
    | '/servicio/'
    | '/servicio/eventos/$id'
    | '/servicio/eventos/nuevo'
    | '/servicio/grupos/$id'
    | '/servicio/grupos/nuevo'
    | '/servicio/eventos/'
    | '/servicio/grupos/'
    | '/servicio/reuniones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacto'
    | '/eventos'
    | '/grupos'
    | '/horarios'
    | '/literatura'
    | '/mapa-del-sitio'
    | '/necesito-ayuda'
    | '/preguntas-frecuentes'
    | '/primera-reunion'
    | '/privacidad'
    | '/que-es-aa'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tengo-un-problema'
    | '/testimonios'
    | '/perfil'
    | '/eventos/$slug'
    | '/grupos/$slug'
    | '/servicio/perfil'
    | '/servicio/usuarios'
    | '/servicio'
    | '/servicio/eventos/$id'
    | '/servicio/eventos/nuevo'
    | '/servicio/grupos/$id'
    | '/servicio/grupos/nuevo'
    | '/servicio/eventos'
    | '/servicio/grupos'
    | '/servicio/reuniones'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contacto'
    | '/eventos'
    | '/grupos'
    | '/horarios'
    | '/literatura'
    | '/mapa-del-sitio'
    | '/necesito-ayuda'
    | '/preguntas-frecuentes'
    | '/primera-reunion'
    | '/privacidad'
    | '/que-es-aa'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tengo-un-problema'
    | '/testimonios'
    | '/_authenticated/perfil'
    | '/_authenticated/servicio'
    | '/eventos/$slug'
    | '/grupos/$slug'
    | '/_authenticated/servicio/perfil'
    | '/_authenticated/servicio/usuarios'
    | '/_authenticated/servicio/'
    | '/_authenticated/servicio/eventos/$id'
    | '/_authenticated/servicio/eventos/nuevo'
    | '/_authenticated/servicio/grupos/$id'
    | '/_authenticated/servicio/grupos/nuevo'
    | '/_authenticated/servicio/eventos/'
    | '/_authenticated/servicio/grupos/'
    | '/_authenticated/servicio/reuniones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactoRoute: typeof ContactoRoute
  EventosRoute: typeof EventosRouteWithChildren
  GruposRoute: typeof GruposRouteWithChildren
  HorariosRoute: typeof HorariosRoute
  LiteraturaRoute: typeof LiteraturaRoute
  MapaDelSitioRoute: typeof MapaDelSitioRoute
  NecesitoAyudaRoute: typeof NecesitoAyudaRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  PrimeraReunionRoute: typeof PrimeraReunionRoute
  PrivacidadRoute: typeof PrivacidadRoute
  QueEsAaRoute: typeof QueEsAaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TengoUnProblemaRoute: typeof TengoUnProblemaRoute
  TestimoniosRoute: typeof TestimoniosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonios': {
      id: '/testimonios'
      path: '/testimonios'
      fullPath: '/testimonios'
      preLoaderRoute: typeof TestimoniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tengo-un-problema': {
      id: '/tengo-un-problema'
      path: '/tengo-un-problema'
      fullPath: '/tengo-un-problema'
      preLoaderRoute: typeof TengoUnProblemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/que-es-aa': {
      id: '/que-es-aa'
      path: '/que-es-aa'
      fullPath: '/que-es-aa'
      preLoaderRoute: typeof QueEsAaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primera-reunion': {
      id: '/primera-reunion'
      path: '/primera-reunion'
      fullPath: '/primera-reunion'
      preLoaderRoute: typeof PrimeraReunionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/necesito-ayuda': {
      id: '/necesito-ayuda'
      path: '/necesito-ayuda'
      fullPath: '/necesito-ayuda'
      preLoaderRoute: typeof NecesitoAyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-del-sitio': {
      id: '/mapa-del-sitio'
      path: '/mapa-del-sitio'
      fullPath: '/mapa-del-sitio'
      preLoaderRoute: typeof MapaDelSitioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literatura': {
      id: '/literatura'
      path: '/literatura'
      fullPath: '/literatura'
      preLoaderRoute: typeof LiteraturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos/$slug': {
      id: '/grupos/$slug'
      path: '/$slug'
      fullPath: '/grupos/$slug'
      preLoaderRoute: typeof GruposSlugRouteImport
      parentRoute: typeof GruposRoute
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof EventosRoute
    }
    '/_authenticated/servicio': {
      id: '/_authenticated/servicio'
      path: '/servicio'
      fullPath: '/servicio'
      preLoaderRoute: typeof AuthenticatedServicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicio/': {
      id: '/_authenticated/servicio/'
      path: '/'
      fullPath: '/servicio/'
      preLoaderRoute: typeof AuthenticatedServicioIndexRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/usuarios': {
      id: '/_authenticated/servicio/usuarios'
      path: '/usuarios'
      fullPath: '/servicio/usuarios'
      preLoaderRoute: typeof AuthenticatedServicioUsuariosRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/perfil': {
      id: '/_authenticated/servicio/perfil'
      path: '/perfil'
      fullPath: '/servicio/perfil'
      preLoaderRoute: typeof AuthenticatedServicioPerfilRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/reuniones/': {
      id: '/_authenticated/servicio/reuniones/'
      path: '/reuniones'
      fullPath: '/servicio/reuniones/'
      preLoaderRoute: typeof AuthenticatedServicioReunionesIndexRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/grupos/': {
      id: '/_authenticated/servicio/grupos/'
      path: '/grupos'
      fullPath: '/servicio/grupos/'
      preLoaderRoute: typeof AuthenticatedServicioGruposIndexRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/eventos/': {
      id: '/_authenticated/servicio/eventos/'
      path: '/eventos'
      fullPath: '/servicio/eventos/'
      preLoaderRoute: typeof AuthenticatedServicioEventosIndexRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/grupos/nuevo': {
      id: '/_authenticated/servicio/grupos/nuevo'
      path: '/grupos/nuevo'
      fullPath: '/servicio/grupos/nuevo'
      preLoaderRoute: typeof AuthenticatedServicioGruposNuevoRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/grupos/$id': {
      id: '/_authenticated/servicio/grupos/$id'
      path: '/grupos/$id'
      fullPath: '/servicio/grupos/$id'
      preLoaderRoute: typeof AuthenticatedServicioGruposIdRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/eventos/nuevo': {
      id: '/_authenticated/servicio/eventos/nuevo'
      path: '/eventos/nuevo'
      fullPath: '/servicio/eventos/nuevo'
      preLoaderRoute: typeof AuthenticatedServicioEventosNuevoRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/eventos/$id': {
      id: '/_authenticated/servicio/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/servicio/eventos/$id'
      preLoaderRoute: typeof AuthenticatedServicioEventosIdRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
  }
}

interface AuthenticatedServicioRouteChildren {
  AuthenticatedServicioPerfilRoute: typeof AuthenticatedServicioPerfilRoute
  AuthenticatedServicioUsuariosRoute: typeof AuthenticatedServicioUsuariosRoute
  AuthenticatedServicioIndexRoute: typeof AuthenticatedServicioIndexRoute
  AuthenticatedServicioEventosIdRoute: typeof AuthenticatedServicioEventosIdRoute
  AuthenticatedServicioEventosNuevoRoute: typeof AuthenticatedServicioEventosNuevoRoute
  AuthenticatedServicioGruposIdRoute: typeof AuthenticatedServicioGruposIdRoute
  AuthenticatedServicioGruposNuevoRoute: typeof AuthenticatedServicioGruposNuevoRoute
  AuthenticatedServicioEventosIndexRoute: typeof AuthenticatedServicioEventosIndexRoute
  AuthenticatedServicioGruposIndexRoute: typeof AuthenticatedServicioGruposIndexRoute
  AuthenticatedServicioReunionesIndexRoute: typeof AuthenticatedServicioReunionesIndexRoute
}

const AuthenticatedServicioRouteChildren: AuthenticatedServicioRouteChildren = {
  AuthenticatedServicioPerfilRoute: AuthenticatedServicioPerfilRoute,
  AuthenticatedServicioUsuariosRoute: AuthenticatedServicioUsuariosRoute,
  AuthenticatedServicioIndexRoute: AuthenticatedServicioIndexRoute,
  AuthenticatedServicioEventosIdRoute: AuthenticatedServicioEventosIdRoute,
  AuthenticatedServicioEventosNuevoRoute:
    AuthenticatedServicioEventosNuevoRoute,
  AuthenticatedServicioGruposIdRoute: AuthenticatedServicioGruposIdRoute,
  AuthenticatedServicioGruposNuevoRoute: AuthenticatedServicioGruposNuevoRoute,
  AuthenticatedServicioEventosIndexRoute:
    AuthenticatedServicioEventosIndexRoute,
  AuthenticatedServicioGruposIndexRoute: AuthenticatedServicioGruposIndexRoute,
  AuthenticatedServicioReunionesIndexRoute:
    AuthenticatedServicioReunionesIndexRoute,
}

const AuthenticatedServicioRouteWithChildren =
  AuthenticatedServicioRoute._addFileChildren(
    AuthenticatedServicioRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedServicioRoute: typeof AuthenticatedServicioRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedServicioRoute: AuthenticatedServicioRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EventosRouteChildren {
  EventosSlugRoute: typeof EventosSlugRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosSlugRoute: EventosSlugRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

interface GruposRouteChildren {
  GruposSlugRoute: typeof GruposSlugRoute
}

const GruposRouteChildren: GruposRouteChildren = {
  GruposSlugRoute: GruposSlugRoute,
}

const GruposRouteWithChildren =
  GruposRoute._addFileChildren(GruposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactoRoute: ContactoRoute,
  EventosRoute: EventosRouteWithChildren,
  GruposRoute: GruposRouteWithChildren,
  HorariosRoute: HorariosRoute,
  LiteraturaRoute: LiteraturaRoute,
  MapaDelSitioRoute: MapaDelSitioRoute,
  NecesitoAyudaRoute: NecesitoAyudaRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  PrimeraReunionRoute: PrimeraReunionRoute,
  PrivacidadRoute: PrivacidadRoute,
  QueEsAaRoute: QueEsAaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TengoUnProblemaRoute: TengoUnProblemaRoute,
  TestimoniosRoute: TestimoniosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
