/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniosRouteImport } from './routes/testimonios'
import { Route as TengoUnProblemaRouteImport } from './routes/tengo-un-problema'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QueEsAaRouteImport } from './routes/que-es-aa'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PrimeraReunionRouteImport } from './routes/primera-reunion'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as NecesitoAyudaRouteImport } from './routes/necesito-ayuda'
import { Route as MiembrosRouteImport } from './routes/miembros'
import { Route as MapaDelSitioRouteImport } from './routes/mapa-del-sitio'
import { Route as LiteraturaRouteImport } from './routes/literatura'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CaribeRouteImport } from './routes/caribe'
import { Route as BuscoAyudaParaMiRouteImport } from './routes/busco-ayuda-para-mi'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as AyudaFamiliarRouteImport } from './routes/ayuda-familiar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MiembrosIndexRouteImport } from './routes/miembros.index'
import { Route as MiembrosResponsabilidadRouteImport } from './routes/miembros.responsabilidad'
import { Route as MiembrosPrincipiosRouteImport } from './routes/miembros.principios'
import { Route as MiembrosOracionesRouteImport } from './routes/miembros.oraciones'
import { Route as MiembrosGruposRouteImport } from './routes/miembros.grupos'
import { Route as MiembrosEventosRouteImport } from './routes/miembros.eventos'
import { Route as MiembrosElGrupoRouteImport } from './routes/miembros.el-grupo'
import { Route as MiembrosDocumentosRouteImport } from './routes/miembros.documentos'
import { Route as MiembrosConferenciaRouteImport } from './routes/miembros.conferencia'
import { Route as MiembrosAsambleaRouteImport } from './routes/miembros.asamblea'
import { Route as MiembrosAreaRouteImport } from './routes/miembros.area'
import { Route as GruposSlugRouteImport } from './routes/grupos.$slug'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as AuthenticatedServicioRouteImport } from './routes/_authenticated/servicio'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as MiembrosPrincipiosIndexRouteImport } from './routes/miembros.principios.index'
import { Route as MiembrosOracionesIndexRouteImport } from './routes/miembros.oraciones.index'
import { Route as AuthenticatedServicioIndexRouteImport } from './routes/_authenticated/servicio.index'
import { Route as MiembrosPrincipiosDoceTradicionesRouteImport } from './routes/miembros.principios.doce-tradiciones'
import { Route as MiembrosPrincipiosDocePasosRouteImport } from './routes/miembros.principios.doce-pasos'
import { Route as MiembrosPrincipiosDoceConceptosRouteImport } from './routes/miembros.principios.doce-conceptos'
import { Route as MiembrosOracionesTercerPasoRouteImport } from './routes/miembros.oraciones.tercer-paso'
import { Route as MiembrosOracionesSerenidadRouteImport } from './routes/miembros.oraciones.serenidad'
import { Route as MiembrosOracionesSeptimoPasoRouteImport } from './routes/miembros.oraciones.septimo-paso'
import { Route as MiembrosOracionesSanFranciscoRouteImport } from './routes/miembros.oraciones.san-francisco'
import { Route as AuthenticatedServicioUsuariosRouteImport } from './routes/_authenticated/servicio.usuarios'
import { Route as AuthenticatedServicioPerfilRouteImport } from './routes/_authenticated/servicio.perfil'
import { Route as AuthenticatedServicioReunionesIndexRouteImport } from './routes/_authenticated/servicio.reuniones.index'
import { Route as AuthenticatedServicioGruposIndexRouteImport } from './routes/_authenticated/servicio.grupos.index'
import { Route as AuthenticatedServicioEventosIndexRouteImport } from './routes/_authenticated/servicio.eventos.index'
import { Route as ApiPublicMembersGateUnlockRouteImport } from './routes/api/public/members-gate/unlock'
import { Route as ApiPublicMembersGateLockRouteImport } from './routes/api/public/members-gate/lock'
import { Route as ApiPublicMembersGateCheckRouteImport } from './routes/api/public/members-gate/check'
import { Route as AuthenticatedServicioGruposNuevoRouteImport } from './routes/_authenticated/servicio.grupos.nuevo'
import { Route as AuthenticatedServicioGruposIdRouteImport } from './routes/_authenticated/servicio.grupos.$id'
import { Route as AuthenticatedServicioEventosNuevoRouteImport } from './routes/_authenticated/servicio.eventos.nuevo'
import { Route as AuthenticatedServicioEventosIdRouteImport } from './routes/_authenticated/servicio.eventos.$id'

const TestimoniosRoute = TestimoniosRouteImport.update({
  id: '/testimonios',
  path: '/testimonios',
  getParentRoute: () => rootRouteImport,
} as any)
const TengoUnProblemaRoute = TengoUnProblemaRouteImport.update({
  id: '/tengo-un-problema',
  path: '/tengo-un-problema',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QueEsAaRoute = QueEsAaRouteImport.update({
  id: '/que-es-aa',
  path: '/que-es-aa',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeraReunionRoute = PrimeraReunionRouteImport.update({
  id: '/primera-reunion',
  path: '/primera-reunion',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const NecesitoAyudaRoute = NecesitoAyudaRouteImport.update({
  id: '/necesito-ayuda',
  path: '/necesito-ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const MiembrosRoute = MiembrosRouteImport.update({
  id: '/miembros',
  path: '/miembros',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaDelSitioRoute = MapaDelSitioRouteImport.update({
  id: '/mapa-del-sitio',
  path: '/mapa-del-sitio',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteraturaRoute = LiteraturaRouteImport.update({
  id: '/literatura',
  path: '/literatura',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CaribeRoute = CaribeRouteImport.update({
  id: '/caribe',
  path: '/caribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscoAyudaParaMiRoute = BuscoAyudaParaMiRouteImport.update({
  id: '/busco-ayuda-para-mi',
  path: '/busco-ayuda-para-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaFamiliarRoute = AyudaFamiliarRouteImport.update({
  id: '/ayuda-familiar',
  path: '/ayuda-familiar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiembrosIndexRoute = MiembrosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MiembrosRoute,
} as any)
const MiembrosResponsabilidadRoute = MiembrosResponsabilidadRouteImport.update({
  id: '/responsabilidad',
  path: '/responsabilidad',
  getParentRoute: () => MiembrosRoute,
} as any)
const MiembrosPrincipiosRoute = MiembrosPrincipiosRouteImport.update({
  id: '/principios',
  path: '/principios',
  getParentRoute: () => MiembrosRoute,
} as any)
const MiembrosOracionesRoute = MiembrosOracionesRouteImport.update({
  id: '/oraciones',
  path: '/oraciones',
  getParentRoute: () => MiembrosRoute,
} as any)
const MiembrosGruposRoute = MiembrosGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => MiembrosRoute,
} as any)
const MiembrosEventosRoute = MiembrosEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => MiembrosRoute,
} as any)
const MiembrosElGrupoRoute = MiembrosElGrupoRouteImport.update({
  id: '/el-grupo',
  path: '/el-grupo',
  getParentRoute: () => MiembrosRoute,
} as any)
const MiembrosDocumentosRoute = MiembrosDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => MiembrosRoute,
} as any)
const MiembrosConferenciaRoute = MiembrosConferenciaRouteImport.update({
  id: '/conferencia',
  path: '/conferencia',
  getParentRoute: () => MiembrosRoute,
} as any)
const MiembrosAsambleaRoute = MiembrosAsambleaRouteImport.update({
  id: '/asamblea',
  path: '/asamblea',
  getParentRoute: () => MiembrosRoute,
} as any)
const MiembrosAreaRoute = MiembrosAreaRouteImport.update({
  id: '/area',
  path: '/area',
  getParentRoute: () => MiembrosRoute,
} as any)
const GruposSlugRoute = GruposSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GruposRoute,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventosRoute,
} as any)
const AuthenticatedServicioRoute = AuthenticatedServicioRouteImport.update({
  id: '/servicio',
  path: '/servicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MiembrosPrincipiosIndexRoute = MiembrosPrincipiosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MiembrosPrincipiosRoute,
} as any)
const MiembrosOracionesIndexRoute = MiembrosOracionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MiembrosOracionesRoute,
} as any)
const AuthenticatedServicioIndexRoute =
  AuthenticatedServicioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const MiembrosPrincipiosDoceTradicionesRoute =
  MiembrosPrincipiosDoceTradicionesRouteImport.update({
    id: '/doce-tradiciones',
    path: '/doce-tradiciones',
    getParentRoute: () => MiembrosPrincipiosRoute,
  } as any)
const MiembrosPrincipiosDocePasosRoute =
  MiembrosPrincipiosDocePasosRouteImport.update({
    id: '/doce-pasos',
    path: '/doce-pasos',
    getParentRoute: () => MiembrosPrincipiosRoute,
  } as any)
const MiembrosPrincipiosDoceConceptosRoute =
  MiembrosPrincipiosDoceConceptosRouteImport.update({
    id: '/doce-conceptos',
    path: '/doce-conceptos',
    getParentRoute: () => MiembrosPrincipiosRoute,
  } as any)
const MiembrosOracionesTercerPasoRoute =
  MiembrosOracionesTercerPasoRouteImport.update({
    id: '/tercer-paso',
    path: '/tercer-paso',
    getParentRoute: () => MiembrosOracionesRoute,
  } as any)
const MiembrosOracionesSerenidadRoute =
  MiembrosOracionesSerenidadRouteImport.update({
    id: '/serenidad',
    path: '/serenidad',
    getParentRoute: () => MiembrosOracionesRoute,
  } as any)
const MiembrosOracionesSeptimoPasoRoute =
  MiembrosOracionesSeptimoPasoRouteImport.update({
    id: '/septimo-paso',
    path: '/septimo-paso',
    getParentRoute: () => MiembrosOracionesRoute,
  } as any)
const MiembrosOracionesSanFranciscoRoute =
  MiembrosOracionesSanFranciscoRouteImport.update({
    id: '/san-francisco',
    path: '/san-francisco',
    getParentRoute: () => MiembrosOracionesRoute,
  } as any)
const AuthenticatedServicioUsuariosRoute =
  AuthenticatedServicioUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioPerfilRoute =
  AuthenticatedServicioPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioReunionesIndexRoute =
  AuthenticatedServicioReunionesIndexRouteImport.update({
    id: '/reuniones/',
    path: '/reuniones/',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioGruposIndexRoute =
  AuthenticatedServicioGruposIndexRouteImport.update({
    id: '/grupos/',
    path: '/grupos/',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioEventosIndexRoute =
  AuthenticatedServicioEventosIndexRouteImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const ApiPublicMembersGateUnlockRoute =
  ApiPublicMembersGateUnlockRouteImport.update({
    id: '/api/public/members-gate/unlock',
    path: '/api/public/members-gate/unlock',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMembersGateLockRoute =
  ApiPublicMembersGateLockRouteImport.update({
    id: '/api/public/members-gate/lock',
    path: '/api/public/members-gate/lock',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMembersGateCheckRoute =
  ApiPublicMembersGateCheckRouteImport.update({
    id: '/api/public/members-gate/check',
    path: '/api/public/members-gate/check',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedServicioGruposNuevoRoute =
  AuthenticatedServicioGruposNuevoRouteImport.update({
    id: '/grupos/nuevo',
    path: '/grupos/nuevo',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioGruposIdRoute =
  AuthenticatedServicioGruposIdRouteImport.update({
    id: '/grupos/$id',
    path: '/grupos/$id',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioEventosNuevoRoute =
  AuthenticatedServicioEventosNuevoRouteImport.update({
    id: '/eventos/nuevo',
    path: '/eventos/nuevo',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)
const AuthenticatedServicioEventosIdRoute =
  AuthenticatedServicioEventosIdRouteImport.update({
    id: '/eventos/$id',
    path: '/eventos/$id',
    getParentRoute: () => AuthenticatedServicioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ayuda-familiar': typeof AyudaFamiliarRoute
  '/bienvenida': typeof BienvenidaRoute
  '/busco-ayuda-para-mi': typeof BuscoAyudaParaMiRoute
  '/caribe': typeof CaribeRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRouteWithChildren
  '/grupos': typeof GruposRouteWithChildren
  '/horarios': typeof HorariosRoute
  '/literatura': typeof LiteraturaRoute
  '/mapa-del-sitio': typeof MapaDelSitioRoute
  '/miembros': typeof MiembrosRouteWithChildren
  '/necesito-ayuda': typeof NecesitoAyudaRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/primera-reunion': typeof PrimeraReunionRoute
  '/privacidad': typeof PrivacidadRoute
  '/que-es-aa': typeof QueEsAaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tengo-un-problema': typeof TengoUnProblemaRoute
  '/testimonios': typeof TestimoniosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/servicio': typeof AuthenticatedServicioRouteWithChildren
  '/eventos/$slug': typeof EventosSlugRoute
  '/grupos/$slug': typeof GruposSlugRoute
  '/miembros/area': typeof MiembrosAreaRoute
  '/miembros/asamblea': typeof MiembrosAsambleaRoute
  '/miembros/conferencia': typeof MiembrosConferenciaRoute
  '/miembros/documentos': typeof MiembrosDocumentosRoute
  '/miembros/el-grupo': typeof MiembrosElGrupoRoute
  '/miembros/eventos': typeof MiembrosEventosRoute
  '/miembros/grupos': typeof MiembrosGruposRoute
  '/miembros/oraciones': typeof MiembrosOracionesRouteWithChildren
  '/miembros/principios': typeof MiembrosPrincipiosRouteWithChildren
  '/miembros/responsabilidad': typeof MiembrosResponsabilidadRoute
  '/miembros/': typeof MiembrosIndexRoute
  '/servicio/perfil': typeof AuthenticatedServicioPerfilRoute
  '/servicio/usuarios': typeof AuthenticatedServicioUsuariosRoute
  '/miembros/oraciones/san-francisco': typeof MiembrosOracionesSanFranciscoRoute
  '/miembros/oraciones/septimo-paso': typeof MiembrosOracionesSeptimoPasoRoute
  '/miembros/oraciones/serenidad': typeof MiembrosOracionesSerenidadRoute
  '/miembros/oraciones/tercer-paso': typeof MiembrosOracionesTercerPasoRoute
  '/miembros/principios/doce-conceptos': typeof MiembrosPrincipiosDoceConceptosRoute
  '/miembros/principios/doce-pasos': typeof MiembrosPrincipiosDocePasosRoute
  '/miembros/principios/doce-tradiciones': typeof MiembrosPrincipiosDoceTradicionesRoute
  '/servicio/': typeof AuthenticatedServicioIndexRoute
  '/miembros/oraciones/': typeof MiembrosOracionesIndexRoute
  '/miembros/principios/': typeof MiembrosPrincipiosIndexRoute
  '/servicio/eventos/$id': typeof AuthenticatedServicioEventosIdRoute
  '/servicio/eventos/nuevo': typeof AuthenticatedServicioEventosNuevoRoute
  '/servicio/grupos/$id': typeof AuthenticatedServicioGruposIdRoute
  '/servicio/grupos/nuevo': typeof AuthenticatedServicioGruposNuevoRoute
  '/api/public/members-gate/check': typeof ApiPublicMembersGateCheckRoute
  '/api/public/members-gate/lock': typeof ApiPublicMembersGateLockRoute
  '/api/public/members-gate/unlock': typeof ApiPublicMembersGateUnlockRoute
  '/servicio/eventos/': typeof AuthenticatedServicioEventosIndexRoute
  '/servicio/grupos/': typeof AuthenticatedServicioGruposIndexRoute
  '/servicio/reuniones/': typeof AuthenticatedServicioReunionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ayuda-familiar': typeof AyudaFamiliarRoute
  '/bienvenida': typeof BienvenidaRoute
  '/busco-ayuda-para-mi': typeof BuscoAyudaParaMiRoute
  '/caribe': typeof CaribeRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRouteWithChildren
  '/grupos': typeof GruposRouteWithChildren
  '/horarios': typeof HorariosRoute
  '/literatura': typeof LiteraturaRoute
  '/mapa-del-sitio': typeof MapaDelSitioRoute
  '/necesito-ayuda': typeof NecesitoAyudaRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/primera-reunion': typeof PrimeraReunionRoute
  '/privacidad': typeof PrivacidadRoute
  '/que-es-aa': typeof QueEsAaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tengo-un-problema': typeof TengoUnProblemaRoute
  '/testimonios': typeof TestimoniosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/grupos/$slug': typeof GruposSlugRoute
  '/miembros/area': typeof MiembrosAreaRoute
  '/miembros/asamblea': typeof MiembrosAsambleaRoute
  '/miembros/conferencia': typeof MiembrosConferenciaRoute
  '/miembros/documentos': typeof MiembrosDocumentosRoute
  '/miembros/el-grupo': typeof MiembrosElGrupoRoute
  '/miembros/eventos': typeof MiembrosEventosRoute
  '/miembros/grupos': typeof MiembrosGruposRoute
  '/miembros/responsabilidad': typeof MiembrosResponsabilidadRoute
  '/miembros': typeof MiembrosIndexRoute
  '/servicio/perfil': typeof AuthenticatedServicioPerfilRoute
  '/servicio/usuarios': typeof AuthenticatedServicioUsuariosRoute
  '/miembros/oraciones/san-francisco': typeof MiembrosOracionesSanFranciscoRoute
  '/miembros/oraciones/septimo-paso': typeof MiembrosOracionesSeptimoPasoRoute
  '/miembros/oraciones/serenidad': typeof MiembrosOracionesSerenidadRoute
  '/miembros/oraciones/tercer-paso': typeof MiembrosOracionesTercerPasoRoute
  '/miembros/principios/doce-conceptos': typeof MiembrosPrincipiosDoceConceptosRoute
  '/miembros/principios/doce-pasos': typeof MiembrosPrincipiosDocePasosRoute
  '/miembros/principios/doce-tradiciones': typeof MiembrosPrincipiosDoceTradicionesRoute
  '/servicio': typeof AuthenticatedServicioIndexRoute
  '/miembros/oraciones': typeof MiembrosOracionesIndexRoute
  '/miembros/principios': typeof MiembrosPrincipiosIndexRoute
  '/servicio/eventos/$id': typeof AuthenticatedServicioEventosIdRoute
  '/servicio/eventos/nuevo': typeof AuthenticatedServicioEventosNuevoRoute
  '/servicio/grupos/$id': typeof AuthenticatedServicioGruposIdRoute
  '/servicio/grupos/nuevo': typeof AuthenticatedServicioGruposNuevoRoute
  '/api/public/members-gate/check': typeof ApiPublicMembersGateCheckRoute
  '/api/public/members-gate/lock': typeof ApiPublicMembersGateLockRoute
  '/api/public/members-gate/unlock': typeof ApiPublicMembersGateUnlockRoute
  '/servicio/eventos': typeof AuthenticatedServicioEventosIndexRoute
  '/servicio/grupos': typeof AuthenticatedServicioGruposIndexRoute
  '/servicio/reuniones': typeof AuthenticatedServicioReunionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/ayuda-familiar': typeof AyudaFamiliarRoute
  '/bienvenida': typeof BienvenidaRoute
  '/busco-ayuda-para-mi': typeof BuscoAyudaParaMiRoute
  '/caribe': typeof CaribeRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRouteWithChildren
  '/grupos': typeof GruposRouteWithChildren
  '/horarios': typeof HorariosRoute
  '/literatura': typeof LiteraturaRoute
  '/mapa-del-sitio': typeof MapaDelSitioRoute
  '/miembros': typeof MiembrosRouteWithChildren
  '/necesito-ayuda': typeof NecesitoAyudaRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/primera-reunion': typeof PrimeraReunionRoute
  '/privacidad': typeof PrivacidadRoute
  '/que-es-aa': typeof QueEsAaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tengo-un-problema': typeof TengoUnProblemaRoute
  '/testimonios': typeof TestimoniosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/servicio': typeof AuthenticatedServicioRouteWithChildren
  '/eventos/$slug': typeof EventosSlugRoute
  '/grupos/$slug': typeof GruposSlugRoute
  '/miembros/area': typeof MiembrosAreaRoute
  '/miembros/asamblea': typeof MiembrosAsambleaRoute
  '/miembros/conferencia': typeof MiembrosConferenciaRoute
  '/miembros/documentos': typeof MiembrosDocumentosRoute
  '/miembros/el-grupo': typeof MiembrosElGrupoRoute
  '/miembros/eventos': typeof MiembrosEventosRoute
  '/miembros/grupos': typeof MiembrosGruposRoute
  '/miembros/oraciones': typeof MiembrosOracionesRouteWithChildren
  '/miembros/principios': typeof MiembrosPrincipiosRouteWithChildren
  '/miembros/responsabilidad': typeof MiembrosResponsabilidadRoute
  '/miembros/': typeof MiembrosIndexRoute
  '/_authenticated/servicio/perfil': typeof AuthenticatedServicioPerfilRoute
  '/_authenticated/servicio/usuarios': typeof AuthenticatedServicioUsuariosRoute
  '/miembros/oraciones/san-francisco': typeof MiembrosOracionesSanFranciscoRoute
  '/miembros/oraciones/septimo-paso': typeof MiembrosOracionesSeptimoPasoRoute
  '/miembros/oraciones/serenidad': typeof MiembrosOracionesSerenidadRoute
  '/miembros/oraciones/tercer-paso': typeof MiembrosOracionesTercerPasoRoute
  '/miembros/principios/doce-conceptos': typeof MiembrosPrincipiosDoceConceptosRoute
  '/miembros/principios/doce-pasos': typeof MiembrosPrincipiosDocePasosRoute
  '/miembros/principios/doce-tradiciones': typeof MiembrosPrincipiosDoceTradicionesRoute
  '/_authenticated/servicio/': typeof AuthenticatedServicioIndexRoute
  '/miembros/oraciones/': typeof MiembrosOracionesIndexRoute
  '/miembros/principios/': typeof MiembrosPrincipiosIndexRoute
  '/_authenticated/servicio/eventos/$id': typeof AuthenticatedServicioEventosIdRoute
  '/_authenticated/servicio/eventos/nuevo': typeof AuthenticatedServicioEventosNuevoRoute
  '/_authenticated/servicio/grupos/$id': typeof AuthenticatedServicioGruposIdRoute
  '/_authenticated/servicio/grupos/nuevo': typeof AuthenticatedServicioGruposNuevoRoute
  '/api/public/members-gate/check': typeof ApiPublicMembersGateCheckRoute
  '/api/public/members-gate/lock': typeof ApiPublicMembersGateLockRoute
  '/api/public/members-gate/unlock': typeof ApiPublicMembersGateUnlockRoute
  '/_authenticated/servicio/eventos/': typeof AuthenticatedServicioEventosIndexRoute
  '/_authenticated/servicio/grupos/': typeof AuthenticatedServicioGruposIndexRoute
  '/_authenticated/servicio/reuniones/': typeof AuthenticatedServicioReunionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ayuda-familiar'
    | '/bienvenida'
    | '/busco-ayuda-para-mi'
    | '/caribe'
    | '/contacto'
    | '/eventos'
    | '/grupos'
    | '/horarios'
    | '/literatura'
    | '/mapa-del-sitio'
    | '/miembros'
    | '/necesito-ayuda'
    | '/preguntas-frecuentes'
    | '/primera-reunion'
    | '/privacidad'
    | '/que-es-aa'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tengo-un-problema'
    | '/testimonios'
    | '/perfil'
    | '/servicio'
    | '/eventos/$slug'
    | '/grupos/$slug'
    | '/miembros/area'
    | '/miembros/asamblea'
    | '/miembros/conferencia'
    | '/miembros/documentos'
    | '/miembros/el-grupo'
    | '/miembros/eventos'
    | '/miembros/grupos'
    | '/miembros/oraciones'
    | '/miembros/principios'
    | '/miembros/responsabilidad'
    | '/miembros/'
    | '/servicio/perfil'
    | '/servicio/usuarios'
    | '/miembros/oraciones/san-francisco'
    | '/miembros/oraciones/septimo-paso'
    | '/miembros/oraciones/serenidad'
    | '/miembros/oraciones/tercer-paso'
    | '/miembros/principios/doce-conceptos'
    | '/miembros/principios/doce-pasos'
    | '/miembros/principios/doce-tradiciones'
    | '/servicio/'
    | '/miembros/oraciones/'
    | '/miembros/principios/'
    | '/servicio/eventos/$id'
    | '/servicio/eventos/nuevo'
    | '/servicio/grupos/$id'
    | '/servicio/grupos/nuevo'
    | '/api/public/members-gate/check'
    | '/api/public/members-gate/lock'
    | '/api/public/members-gate/unlock'
    | '/servicio/eventos/'
    | '/servicio/grupos/'
    | '/servicio/reuniones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ayuda-familiar'
    | '/bienvenida'
    | '/busco-ayuda-para-mi'
    | '/caribe'
    | '/contacto'
    | '/eventos'
    | '/grupos'
    | '/horarios'
    | '/literatura'
    | '/mapa-del-sitio'
    | '/necesito-ayuda'
    | '/preguntas-frecuentes'
    | '/primera-reunion'
    | '/privacidad'
    | '/que-es-aa'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tengo-un-problema'
    | '/testimonios'
    | '/perfil'
    | '/eventos/$slug'
    | '/grupos/$slug'
    | '/miembros/area'
    | '/miembros/asamblea'
    | '/miembros/conferencia'
    | '/miembros/documentos'
    | '/miembros/el-grupo'
    | '/miembros/eventos'
    | '/miembros/grupos'
    | '/miembros/responsabilidad'
    | '/miembros'
    | '/servicio/perfil'
    | '/servicio/usuarios'
    | '/miembros/oraciones/san-francisco'
    | '/miembros/oraciones/septimo-paso'
    | '/miembros/oraciones/serenidad'
    | '/miembros/oraciones/tercer-paso'
    | '/miembros/principios/doce-conceptos'
    | '/miembros/principios/doce-pasos'
    | '/miembros/principios/doce-tradiciones'
    | '/servicio'
    | '/miembros/oraciones'
    | '/miembros/principios'
    | '/servicio/eventos/$id'
    | '/servicio/eventos/nuevo'
    | '/servicio/grupos/$id'
    | '/servicio/grupos/nuevo'
    | '/api/public/members-gate/check'
    | '/api/public/members-gate/lock'
    | '/api/public/members-gate/unlock'
    | '/servicio/eventos'
    | '/servicio/grupos'
    | '/servicio/reuniones'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/ayuda-familiar'
    | '/bienvenida'
    | '/busco-ayuda-para-mi'
    | '/caribe'
    | '/contacto'
    | '/eventos'
    | '/grupos'
    | '/horarios'
    | '/literatura'
    | '/mapa-del-sitio'
    | '/miembros'
    | '/necesito-ayuda'
    | '/preguntas-frecuentes'
    | '/primera-reunion'
    | '/privacidad'
    | '/que-es-aa'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tengo-un-problema'
    | '/testimonios'
    | '/_authenticated/perfil'
    | '/_authenticated/servicio'
    | '/eventos/$slug'
    | '/grupos/$slug'
    | '/miembros/area'
    | '/miembros/asamblea'
    | '/miembros/conferencia'
    | '/miembros/documentos'
    | '/miembros/el-grupo'
    | '/miembros/eventos'
    | '/miembros/grupos'
    | '/miembros/oraciones'
    | '/miembros/principios'
    | '/miembros/responsabilidad'
    | '/miembros/'
    | '/_authenticated/servicio/perfil'
    | '/_authenticated/servicio/usuarios'
    | '/miembros/oraciones/san-francisco'
    | '/miembros/oraciones/septimo-paso'
    | '/miembros/oraciones/serenidad'
    | '/miembros/oraciones/tercer-paso'
    | '/miembros/principios/doce-conceptos'
    | '/miembros/principios/doce-pasos'
    | '/miembros/principios/doce-tradiciones'
    | '/_authenticated/servicio/'
    | '/miembros/oraciones/'
    | '/miembros/principios/'
    | '/_authenticated/servicio/eventos/$id'
    | '/_authenticated/servicio/eventos/nuevo'
    | '/_authenticated/servicio/grupos/$id'
    | '/_authenticated/servicio/grupos/nuevo'
    | '/api/public/members-gate/check'
    | '/api/public/members-gate/lock'
    | '/api/public/members-gate/unlock'
    | '/_authenticated/servicio/eventos/'
    | '/_authenticated/servicio/grupos/'
    | '/_authenticated/servicio/reuniones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AyudaFamiliarRoute: typeof AyudaFamiliarRoute
  BienvenidaRoute: typeof BienvenidaRoute
  BuscoAyudaParaMiRoute: typeof BuscoAyudaParaMiRoute
  CaribeRoute: typeof CaribeRoute
  ContactoRoute: typeof ContactoRoute
  EventosRoute: typeof EventosRouteWithChildren
  GruposRoute: typeof GruposRouteWithChildren
  HorariosRoute: typeof HorariosRoute
  LiteraturaRoute: typeof LiteraturaRoute
  MapaDelSitioRoute: typeof MapaDelSitioRoute
  MiembrosRoute: typeof MiembrosRouteWithChildren
  NecesitoAyudaRoute: typeof NecesitoAyudaRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  PrimeraReunionRoute: typeof PrimeraReunionRoute
  PrivacidadRoute: typeof PrivacidadRoute
  QueEsAaRoute: typeof QueEsAaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TengoUnProblemaRoute: typeof TengoUnProblemaRoute
  TestimoniosRoute: typeof TestimoniosRoute
  ApiPublicMembersGateCheckRoute: typeof ApiPublicMembersGateCheckRoute
  ApiPublicMembersGateLockRoute: typeof ApiPublicMembersGateLockRoute
  ApiPublicMembersGateUnlockRoute: typeof ApiPublicMembersGateUnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonios': {
      id: '/testimonios'
      path: '/testimonios'
      fullPath: '/testimonios'
      preLoaderRoute: typeof TestimoniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tengo-un-problema': {
      id: '/tengo-un-problema'
      path: '/tengo-un-problema'
      fullPath: '/tengo-un-problema'
      preLoaderRoute: typeof TengoUnProblemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/que-es-aa': {
      id: '/que-es-aa'
      path: '/que-es-aa'
      fullPath: '/que-es-aa'
      preLoaderRoute: typeof QueEsAaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primera-reunion': {
      id: '/primera-reunion'
      path: '/primera-reunion'
      fullPath: '/primera-reunion'
      preLoaderRoute: typeof PrimeraReunionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/necesito-ayuda': {
      id: '/necesito-ayuda'
      path: '/necesito-ayuda'
      fullPath: '/necesito-ayuda'
      preLoaderRoute: typeof NecesitoAyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miembros': {
      id: '/miembros'
      path: '/miembros'
      fullPath: '/miembros'
      preLoaderRoute: typeof MiembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-del-sitio': {
      id: '/mapa-del-sitio'
      path: '/mapa-del-sitio'
      fullPath: '/mapa-del-sitio'
      preLoaderRoute: typeof MapaDelSitioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literatura': {
      id: '/literatura'
      path: '/literatura'
      fullPath: '/literatura'
      preLoaderRoute: typeof LiteraturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caribe': {
      id: '/caribe'
      path: '/caribe'
      fullPath: '/caribe'
      preLoaderRoute: typeof CaribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busco-ayuda-para-mi': {
      id: '/busco-ayuda-para-mi'
      path: '/busco-ayuda-para-mi'
      fullPath: '/busco-ayuda-para-mi'
      preLoaderRoute: typeof BuscoAyudaParaMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenida': {
      id: '/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof BienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda-familiar': {
      id: '/ayuda-familiar'
      path: '/ayuda-familiar'
      fullPath: '/ayuda-familiar'
      preLoaderRoute: typeof AyudaFamiliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miembros/': {
      id: '/miembros/'
      path: '/'
      fullPath: '/miembros/'
      preLoaderRoute: typeof MiembrosIndexRouteImport
      parentRoute: typeof MiembrosRoute
    }
    '/miembros/responsabilidad': {
      id: '/miembros/responsabilidad'
      path: '/responsabilidad'
      fullPath: '/miembros/responsabilidad'
      preLoaderRoute: typeof MiembrosResponsabilidadRouteImport
      parentRoute: typeof MiembrosRoute
    }
    '/miembros/principios': {
      id: '/miembros/principios'
      path: '/principios'
      fullPath: '/miembros/principios'
      preLoaderRoute: typeof MiembrosPrincipiosRouteImport
      parentRoute: typeof MiembrosRoute
    }
    '/miembros/oraciones': {
      id: '/miembros/oraciones'
      path: '/oraciones'
      fullPath: '/miembros/oraciones'
      preLoaderRoute: typeof MiembrosOracionesRouteImport
      parentRoute: typeof MiembrosRoute
    }
    '/miembros/grupos': {
      id: '/miembros/grupos'
      path: '/grupos'
      fullPath: '/miembros/grupos'
      preLoaderRoute: typeof MiembrosGruposRouteImport
      parentRoute: typeof MiembrosRoute
    }
    '/miembros/eventos': {
      id: '/miembros/eventos'
      path: '/eventos'
      fullPath: '/miembros/eventos'
      preLoaderRoute: typeof MiembrosEventosRouteImport
      parentRoute: typeof MiembrosRoute
    }
    '/miembros/el-grupo': {
      id: '/miembros/el-grupo'
      path: '/el-grupo'
      fullPath: '/miembros/el-grupo'
      preLoaderRoute: typeof MiembrosElGrupoRouteImport
      parentRoute: typeof MiembrosRoute
    }
    '/miembros/documentos': {
      id: '/miembros/documentos'
      path: '/documentos'
      fullPath: '/miembros/documentos'
      preLoaderRoute: typeof MiembrosDocumentosRouteImport
      parentRoute: typeof MiembrosRoute
    }
    '/miembros/conferencia': {
      id: '/miembros/conferencia'
      path: '/conferencia'
      fullPath: '/miembros/conferencia'
      preLoaderRoute: typeof MiembrosConferenciaRouteImport
      parentRoute: typeof MiembrosRoute
    }
    '/miembros/asamblea': {
      id: '/miembros/asamblea'
      path: '/asamblea'
      fullPath: '/miembros/asamblea'
      preLoaderRoute: typeof MiembrosAsambleaRouteImport
      parentRoute: typeof MiembrosRoute
    }
    '/miembros/area': {
      id: '/miembros/area'
      path: '/area'
      fullPath: '/miembros/area'
      preLoaderRoute: typeof MiembrosAreaRouteImport
      parentRoute: typeof MiembrosRoute
    }
    '/grupos/$slug': {
      id: '/grupos/$slug'
      path: '/$slug'
      fullPath: '/grupos/$slug'
      preLoaderRoute: typeof GruposSlugRouteImport
      parentRoute: typeof GruposRoute
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof EventosRoute
    }
    '/_authenticated/servicio': {
      id: '/_authenticated/servicio'
      path: '/servicio'
      fullPath: '/servicio'
      preLoaderRoute: typeof AuthenticatedServicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/miembros/principios/': {
      id: '/miembros/principios/'
      path: '/'
      fullPath: '/miembros/principios/'
      preLoaderRoute: typeof MiembrosPrincipiosIndexRouteImport
      parentRoute: typeof MiembrosPrincipiosRoute
    }
    '/miembros/oraciones/': {
      id: '/miembros/oraciones/'
      path: '/'
      fullPath: '/miembros/oraciones/'
      preLoaderRoute: typeof MiembrosOracionesIndexRouteImport
      parentRoute: typeof MiembrosOracionesRoute
    }
    '/_authenticated/servicio/': {
      id: '/_authenticated/servicio/'
      path: '/'
      fullPath: '/servicio/'
      preLoaderRoute: typeof AuthenticatedServicioIndexRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/miembros/principios/doce-tradiciones': {
      id: '/miembros/principios/doce-tradiciones'
      path: '/doce-tradiciones'
      fullPath: '/miembros/principios/doce-tradiciones'
      preLoaderRoute: typeof MiembrosPrincipiosDoceTradicionesRouteImport
      parentRoute: typeof MiembrosPrincipiosRoute
    }
    '/miembros/principios/doce-pasos': {
      id: '/miembros/principios/doce-pasos'
      path: '/doce-pasos'
      fullPath: '/miembros/principios/doce-pasos'
      preLoaderRoute: typeof MiembrosPrincipiosDocePasosRouteImport
      parentRoute: typeof MiembrosPrincipiosRoute
    }
    '/miembros/principios/doce-conceptos': {
      id: '/miembros/principios/doce-conceptos'
      path: '/doce-conceptos'
      fullPath: '/miembros/principios/doce-conceptos'
      preLoaderRoute: typeof MiembrosPrincipiosDoceConceptosRouteImport
      parentRoute: typeof MiembrosPrincipiosRoute
    }
    '/miembros/oraciones/tercer-paso': {
      id: '/miembros/oraciones/tercer-paso'
      path: '/tercer-paso'
      fullPath: '/miembros/oraciones/tercer-paso'
      preLoaderRoute: typeof MiembrosOracionesTercerPasoRouteImport
      parentRoute: typeof MiembrosOracionesRoute
    }
    '/miembros/oraciones/serenidad': {
      id: '/miembros/oraciones/serenidad'
      path: '/serenidad'
      fullPath: '/miembros/oraciones/serenidad'
      preLoaderRoute: typeof MiembrosOracionesSerenidadRouteImport
      parentRoute: typeof MiembrosOracionesRoute
    }
    '/miembros/oraciones/septimo-paso': {
      id: '/miembros/oraciones/septimo-paso'
      path: '/septimo-paso'
      fullPath: '/miembros/oraciones/septimo-paso'
      preLoaderRoute: typeof MiembrosOracionesSeptimoPasoRouteImport
      parentRoute: typeof MiembrosOracionesRoute
    }
    '/miembros/oraciones/san-francisco': {
      id: '/miembros/oraciones/san-francisco'
      path: '/san-francisco'
      fullPath: '/miembros/oraciones/san-francisco'
      preLoaderRoute: typeof MiembrosOracionesSanFranciscoRouteImport
      parentRoute: typeof MiembrosOracionesRoute
    }
    '/_authenticated/servicio/usuarios': {
      id: '/_authenticated/servicio/usuarios'
      path: '/usuarios'
      fullPath: '/servicio/usuarios'
      preLoaderRoute: typeof AuthenticatedServicioUsuariosRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/perfil': {
      id: '/_authenticated/servicio/perfil'
      path: '/perfil'
      fullPath: '/servicio/perfil'
      preLoaderRoute: typeof AuthenticatedServicioPerfilRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/reuniones/': {
      id: '/_authenticated/servicio/reuniones/'
      path: '/reuniones'
      fullPath: '/servicio/reuniones/'
      preLoaderRoute: typeof AuthenticatedServicioReunionesIndexRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/grupos/': {
      id: '/_authenticated/servicio/grupos/'
      path: '/grupos'
      fullPath: '/servicio/grupos/'
      preLoaderRoute: typeof AuthenticatedServicioGruposIndexRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/eventos/': {
      id: '/_authenticated/servicio/eventos/'
      path: '/eventos'
      fullPath: '/servicio/eventos/'
      preLoaderRoute: typeof AuthenticatedServicioEventosIndexRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/api/public/members-gate/unlock': {
      id: '/api/public/members-gate/unlock'
      path: '/api/public/members-gate/unlock'
      fullPath: '/api/public/members-gate/unlock'
      preLoaderRoute: typeof ApiPublicMembersGateUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/members-gate/lock': {
      id: '/api/public/members-gate/lock'
      path: '/api/public/members-gate/lock'
      fullPath: '/api/public/members-gate/lock'
      preLoaderRoute: typeof ApiPublicMembersGateLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/members-gate/check': {
      id: '/api/public/members-gate/check'
      path: '/api/public/members-gate/check'
      fullPath: '/api/public/members-gate/check'
      preLoaderRoute: typeof ApiPublicMembersGateCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/servicio/grupos/nuevo': {
      id: '/_authenticated/servicio/grupos/nuevo'
      path: '/grupos/nuevo'
      fullPath: '/servicio/grupos/nuevo'
      preLoaderRoute: typeof AuthenticatedServicioGruposNuevoRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/grupos/$id': {
      id: '/_authenticated/servicio/grupos/$id'
      path: '/grupos/$id'
      fullPath: '/servicio/grupos/$id'
      preLoaderRoute: typeof AuthenticatedServicioGruposIdRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/eventos/nuevo': {
      id: '/_authenticated/servicio/eventos/nuevo'
      path: '/eventos/nuevo'
      fullPath: '/servicio/eventos/nuevo'
      preLoaderRoute: typeof AuthenticatedServicioEventosNuevoRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
    '/_authenticated/servicio/eventos/$id': {
      id: '/_authenticated/servicio/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/servicio/eventos/$id'
      preLoaderRoute: typeof AuthenticatedServicioEventosIdRouteImport
      parentRoute: typeof AuthenticatedServicioRoute
    }
  }
}

interface AuthenticatedServicioRouteChildren {
  AuthenticatedServicioPerfilRoute: typeof AuthenticatedServicioPerfilRoute
  AuthenticatedServicioUsuariosRoute: typeof AuthenticatedServicioUsuariosRoute
  AuthenticatedServicioIndexRoute: typeof AuthenticatedServicioIndexRoute
  AuthenticatedServicioEventosIdRoute: typeof AuthenticatedServicioEventosIdRoute
  AuthenticatedServicioEventosNuevoRoute: typeof AuthenticatedServicioEventosNuevoRoute
  AuthenticatedServicioGruposIdRoute: typeof AuthenticatedServicioGruposIdRoute
  AuthenticatedServicioGruposNuevoRoute: typeof AuthenticatedServicioGruposNuevoRoute
  AuthenticatedServicioEventosIndexRoute: typeof AuthenticatedServicioEventosIndexRoute
  AuthenticatedServicioGruposIndexRoute: typeof AuthenticatedServicioGruposIndexRoute
  AuthenticatedServicioReunionesIndexRoute: typeof AuthenticatedServicioReunionesIndexRoute
}

const AuthenticatedServicioRouteChildren: AuthenticatedServicioRouteChildren = {
  AuthenticatedServicioPerfilRoute: AuthenticatedServicioPerfilRoute,
  AuthenticatedServicioUsuariosRoute: AuthenticatedServicioUsuariosRoute,
  AuthenticatedServicioIndexRoute: AuthenticatedServicioIndexRoute,
  AuthenticatedServicioEventosIdRoute: AuthenticatedServicioEventosIdRoute,
  AuthenticatedServicioEventosNuevoRoute:
    AuthenticatedServicioEventosNuevoRoute,
  AuthenticatedServicioGruposIdRoute: AuthenticatedServicioGruposIdRoute,
  AuthenticatedServicioGruposNuevoRoute: AuthenticatedServicioGruposNuevoRoute,
  AuthenticatedServicioEventosIndexRoute:
    AuthenticatedServicioEventosIndexRoute,
  AuthenticatedServicioGruposIndexRoute: AuthenticatedServicioGruposIndexRoute,
  AuthenticatedServicioReunionesIndexRoute:
    AuthenticatedServicioReunionesIndexRoute,
}

const AuthenticatedServicioRouteWithChildren =
  AuthenticatedServicioRoute._addFileChildren(
    AuthenticatedServicioRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedServicioRoute: typeof AuthenticatedServicioRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedServicioRoute: AuthenticatedServicioRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EventosRouteChildren {
  EventosSlugRoute: typeof EventosSlugRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosSlugRoute: EventosSlugRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

interface GruposRouteChildren {
  GruposSlugRoute: typeof GruposSlugRoute
}

const GruposRouteChildren: GruposRouteChildren = {
  GruposSlugRoute: GruposSlugRoute,
}

const GruposRouteWithChildren =
  GruposRoute._addFileChildren(GruposRouteChildren)

interface MiembrosOracionesRouteChildren {
  MiembrosOracionesSanFranciscoRoute: typeof MiembrosOracionesSanFranciscoRoute
  MiembrosOracionesSeptimoPasoRoute: typeof MiembrosOracionesSeptimoPasoRoute
  MiembrosOracionesSerenidadRoute: typeof MiembrosOracionesSerenidadRoute
  MiembrosOracionesTercerPasoRoute: typeof MiembrosOracionesTercerPasoRoute
  MiembrosOracionesIndexRoute: typeof MiembrosOracionesIndexRoute
}

const MiembrosOracionesRouteChildren: MiembrosOracionesRouteChildren = {
  MiembrosOracionesSanFranciscoRoute: MiembrosOracionesSanFranciscoRoute,
  MiembrosOracionesSeptimoPasoRoute: MiembrosOracionesSeptimoPasoRoute,
  MiembrosOracionesSerenidadRoute: MiembrosOracionesSerenidadRoute,
  MiembrosOracionesTercerPasoRoute: MiembrosOracionesTercerPasoRoute,
  MiembrosOracionesIndexRoute: MiembrosOracionesIndexRoute,
}

const MiembrosOracionesRouteWithChildren =
  MiembrosOracionesRoute._addFileChildren(MiembrosOracionesRouteChildren)

interface MiembrosPrincipiosRouteChildren {
  MiembrosPrincipiosDoceConceptosRoute: typeof MiembrosPrincipiosDoceConceptosRoute
  MiembrosPrincipiosDocePasosRoute: typeof MiembrosPrincipiosDocePasosRoute
  MiembrosPrincipiosDoceTradicionesRoute: typeof MiembrosPrincipiosDoceTradicionesRoute
  MiembrosPrincipiosIndexRoute: typeof MiembrosPrincipiosIndexRoute
}

const MiembrosPrincipiosRouteChildren: MiembrosPrincipiosRouteChildren = {
  MiembrosPrincipiosDoceConceptosRoute: MiembrosPrincipiosDoceConceptosRoute,
  MiembrosPrincipiosDocePasosRoute: MiembrosPrincipiosDocePasosRoute,
  MiembrosPrincipiosDoceTradicionesRoute:
    MiembrosPrincipiosDoceTradicionesRoute,
  MiembrosPrincipiosIndexRoute: MiembrosPrincipiosIndexRoute,
}

const MiembrosPrincipiosRouteWithChildren =
  MiembrosPrincipiosRoute._addFileChildren(MiembrosPrincipiosRouteChildren)

interface MiembrosRouteChildren {
  MiembrosAreaRoute: typeof MiembrosAreaRoute
  MiembrosAsambleaRoute: typeof MiembrosAsambleaRoute
  MiembrosConferenciaRoute: typeof MiembrosConferenciaRoute
  MiembrosDocumentosRoute: typeof MiembrosDocumentosRoute
  MiembrosElGrupoRoute: typeof MiembrosElGrupoRoute
  MiembrosEventosRoute: typeof MiembrosEventosRoute
  MiembrosGruposRoute: typeof MiembrosGruposRoute
  MiembrosOracionesRoute: typeof MiembrosOracionesRouteWithChildren
  MiembrosPrincipiosRoute: typeof MiembrosPrincipiosRouteWithChildren
  MiembrosResponsabilidadRoute: typeof MiembrosResponsabilidadRoute
  MiembrosIndexRoute: typeof MiembrosIndexRoute
}

const MiembrosRouteChildren: MiembrosRouteChildren = {
  MiembrosAreaRoute: MiembrosAreaRoute,
  MiembrosAsambleaRoute: MiembrosAsambleaRoute,
  MiembrosConferenciaRoute: MiembrosConferenciaRoute,
  MiembrosDocumentosRoute: MiembrosDocumentosRoute,
  MiembrosElGrupoRoute: MiembrosElGrupoRoute,
  MiembrosEventosRoute: MiembrosEventosRoute,
  MiembrosGruposRoute: MiembrosGruposRoute,
  MiembrosOracionesRoute: MiembrosOracionesRouteWithChildren,
  MiembrosPrincipiosRoute: MiembrosPrincipiosRouteWithChildren,
  MiembrosResponsabilidadRoute: MiembrosResponsabilidadRoute,
  MiembrosIndexRoute: MiembrosIndexRoute,
}

const MiembrosRouteWithChildren = MiembrosRoute._addFileChildren(
  MiembrosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AyudaFamiliarRoute: AyudaFamiliarRoute,
  BienvenidaRoute: BienvenidaRoute,
  BuscoAyudaParaMiRoute: BuscoAyudaParaMiRoute,
  CaribeRoute: CaribeRoute,
  ContactoRoute: ContactoRoute,
  EventosRoute: EventosRouteWithChildren,
  GruposRoute: GruposRouteWithChildren,
  HorariosRoute: HorariosRoute,
  LiteraturaRoute: LiteraturaRoute,
  MapaDelSitioRoute: MapaDelSitioRoute,
  MiembrosRoute: MiembrosRouteWithChildren,
  NecesitoAyudaRoute: NecesitoAyudaRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  PrimeraReunionRoute: PrimeraReunionRoute,
  PrivacidadRoute: PrivacidadRoute,
  QueEsAaRoute: QueEsAaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TengoUnProblemaRoute: TengoUnProblemaRoute,
  TestimoniosRoute: TestimoniosRoute,
  ApiPublicMembersGateCheckRoute: ApiPublicMembersGateCheckRoute,
  ApiPublicMembersGateLockRoute: ApiPublicMembersGateLockRoute,
  ApiPublicMembersGateUnlockRoute: ApiPublicMembersGateUnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
